[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
auto-format = true

[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = [
  "--stdin",
  "input.rb",
  "--autocorrect",
  "--stderr",
  "--fail-level",
  "fatal",
  "--server",
  "--editor",
] }

[language-server.pyright]
command = "pyright-langserver"
