[[language]]
name = "markdown"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
auto-format = true

[[language]]
name = "python"
auto-format = true
language-servers = [ "pyright", "ruff" ]

[language-server.pyright]
command = "pyright-langserver"

