[user] 
    email = mari@adobe.com
[url "ssh://git@git.corp.adobe.com/"]
	insteadOf = https://git.corp.adobe.com/
[url "adobe:OneAdobe"]
    insteadOf = git@github.com:OneAdobe
[url "adobe:OneAdobe"]
    insteadOf = https://github.com/OneAdobe
[url "adobe:Adobe-AEM-Foundation"]
    insteadOf = git@github.com:Adobe-AEM-Foundation
[url "adobe:Adobe-AEM-Foundation"]
    insteadOf = https://github.com/Adobe-AEM-Foundation
